package com.example;

@javax.annotation.Generated("generated by class com.rtr.alchemy.transmute.MockIdentityAnnotationProcessor")
public class SimpleIdentityMapper implements com.rtr.alchemy.mapping.Mapper<com.example.SimpleIdentityDto, com.example.SimpleIdentity> {
    @java.lang.Override
    public com.example.SimpleIdentity fromDto(com.example.SimpleIdentityDto source) {
        return new com.example.SimpleIdentity(source.getName(), source.getValue(), source.isActive());
    }

    @java.lang.Override
    public com.example.SimpleIdentityDto toDto(com.example.SimpleIdentity source) {
        return new com.example.SimpleIdentityDto(source.getName(), source.getValue(), source.isActive());
    }
}