package com.example;

@javax.annotation.Generated("generated by class com.rtr.alchemy.transmute.MockIdentityAnnotationProcessor")
@com.fasterxml.jackson.annotation.JsonTypeName("simple")
public class SimpleIdentityDto extends com.rtr.alchemy.dto.identities.IdentityDto {
    private final java.lang.String name;
    private final java.lang.String value;
    private final boolean active;

    @com.fasterxml.jackson.annotation.JsonCreator
    public SimpleIdentityDto(@com.fasterxml.jackson.annotation.JsonProperty("name") java.lang.String name, @com.fasterxml.jackson.annotation.JsonProperty("value") java.lang.String value, @com.fasterxml.jackson.annotation.JsonProperty("active") boolean active) {
        this.name = name;
        this.value = value;
        this.active = active;
    }

    public java.lang.String getName() {
        return name;
    }
    public java.lang.String getValue() {
        return value;
    }
    public boolean isActive() {
        return active;
    }
}
