server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 8001

identities:
  - com.rtr.alchemy.example.identities.User

provider:
  type: com.rtr.alchemy.example.provider.MemoryDatabaseConfiguration